site_name: Curve Resources
site_url: https://resources.curve.fi/
site_author: CurveFi

plugins:
  - search
  - autolinks
  - typeset
  - minify:
      minify_html: true


# extension
markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  custom_dir: overrides
  include_search_page: false
  search_index_only: true
  font:
    text: Roboto
    code: Roboto Mono
  logo: "images/lama.png"
  favicon: "images/lama.png"
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
  palette:
    # - media: "(prefers-color-scheme: dark)"
    - scheme: default
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # - media: "(prefers-color-scheme: light)"
    - scheme: slate
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/curvefi
      name: Telegram
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/curvefinance
      name: X
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rgrfS7W
      name: Discord
    - icon: fontawesome/brands/youtube
      link: http://www.youtube.com/c/CurveFinance
      name: YouTube

extra_css:
  - stylesheets/extra.css
  #- stylesheets/highcharts.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_name: CurveDocs/curve-resources
repo_url: https://github.com/CurveDocs/curve-resources


nav:
  - Getting Started:
    - Understanding Curve (v1): base-features/understanding-curve.md  
    - Understanding CryptoPools (v2): base-features/understanding-crypto-pools.md  
  - CRV Token:
    - Understanding CRV: crv-token/crv-basics.md
    - Tokenomics: crv-token/crv-tokenomics.md
    - Claiming Trading Fees: crv-token/claiming-trading-fees.md
  - veCRV:
    - Overview: vecrv/overview.md
    - Locking CRV: vecrv/locking-your-crv.md
    - Vote-locking FAQ: vecrv/vote-locking-boost.md
  - Curve Stablecoin (crvUSD):
    - Understanding crvUSD: crvusd/understanding-crvusd.md
    - Loan Creation & Management: crvusd/loan-creation.md
    - Loan Details & Concepts: crvusd/loan-details.md
    - crvUSD FAQ: crvusd/faq.md
  - Liquidity Providers:
    - Understanding curve pools: lp/understanding-curve-pools.md
    - Pools: lp/pools.md
    - Deposit FAQ: lp/deposit-faqs.md
    - Calculating yield: lp/calculating-yield.md
    - Charts and Pool Activity: lp/charts_poolactivity.md
    - Depositing:
      - Overview: lp/depositing/depositing.md
      - Despositing into the tri-pool: lp/depositing/depositing-into-the-tri-pool.md
      - Despositing into a metapool: lp/depositing/depositing-into-a-metapool.md
      - Despositing into the susd-pool: lp/depositing/depositing-into-the-susd-pool.md
      - Despositing into a cryptoswap-pool: lp/depositing/depositing-into-a-cryptoswap-pool.md
      - Despositing into a tricrypto-pool: lp/depositing/depositing-into-a-tricrypto-pool.md
  - Reward Gauges:
    - Understanding gauges: reward-gauges/understanding-gauges.md
    - Creating a pool gauge: reward-gauges/creating-a-pool-gauge.md
    - Boosting your CRV rewards: reward-gauges/boosting-your-crv-rewards.md
    - Gauge weights: reward-gauges/gauge-weights.md
    - Permissionless rewards: reward-gauges/permissionless-rewards.md
  - Governance:
    - Understanding governance: governance/understanding-governance.md
    - Voting: governance/voting.md
    - Snapshot: governance/snapshot.md
    - Proposals:
      - Community fund: governance/proposals/community-fund.md
      - Creating a DAO proposal: governance/proposals/creating-a-dao-proposal.md
  - Multi-Chain:
    - CRV: multichain/crv.md
    - crvUSD: multichain/crvusd.md
    - Understanding multi-chain: multichain/understanding-multichain.md
    - Bridging funds: multichain/bridging-funds.md
  - Factory Pools:
    - Understanding pool factory: factory-pools/pool-factory.md
    - Creating a stableswap pool: factory-pools/creating-a-stableswap-pool.md
    - Creating a stableswap-NG pool: factory-pools/creating-a-stableswap-ng-pool.md
    - Creating a cryptoswap pool: factory-pools/creating-a-cryptoswap-pool.md
    - Understanding oracles: factory-pools/understanding-oracles.md
  - Troubleshooting:
    - Support: troubleshooting/support.md
    - Cross-Asset swaps: troubleshooting/cross-asset-swaps.md
    - Recovering cross-asset swaps: troubleshooting/recovering-a-cross-asset-swap.md
    - Dropping and replacing a stuck transaction: troubleshooting/dropping-and-replacing-a-stuck-transaction.md
    - Disabling crypto wallets in brave: troubleshooting/disabling-crypto-wallets-in-brave.md
  - Appendix:
    - Security: faq/security.md
    - Glossary: faq/glossary.md
  - Links:
    - Curve.fi: https://curve.fi/#/ethereum/swap
    - Curve DAO: https://dao.curve.fi/
    - Github: https://github.com/curvefi/
    - Governance Forum: https://gov.curve.fi/
    - Twitter: https://twitter.com/curvefinance
    - Technical Docs: https://docs.curve.fi/