site_name: Curve Resources
site_url: https://resources.curve.fi/
site_author: CurveFi

plugins:
  - search
  - autolinks
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        "crv-token/crv-basics.md": "crv-token/faq.md"
        "crv-token/crv-tokenomics.md": "crv-token/supply-distribution.md"
        "lending/about.md": "lending/overview.md"
        "lending/loan-creation.md": "lending/how-to-borrow.md"
        "lending/supplying-assets.md": "lending/how-to-supply.md"
        "crvusd/loan-management.md": "crvusd/loan-strategies.md"
        "crvusd/loan-details.md": "crvusd/loan-concepts.md"
        "resources/branding.md": "glossary-branding/branding.md"
        "resources/glossary.md": "glossary-branding/glossary.md"
        "resources/risks/pool.md": "risks-security/risks/pool.md"
        "resources/risks/crvusd.md": "risks-security/risks/crvusd.md"
        "resources/risks/lending.md": "risks-security/risks/lending.md"
        "resources/security.md": "risks-security/security.md"
        "governance/fee-collection-distribution.md": "vecrv/overview.md"
        "crv-token/claiming-trading-fees.md": "vecrv/claiming-trading-fees.md"
        "lending/understanding-lending.md": "lending/overview.md"
        "crvusd/loan-details.md": "crvusd/loan-concepts.md"


# extension
markdown_extensions:
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - meta
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  custom_dir: overrides
  include_search_page: false
  search_index_only: true
  font:
    text: Roboto
    code: Roboto Mono
  logo: "images/lama.png"
  favicon: "images/lama.png"
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.tabs.link
    - content.footnote.tooltips
    - navigation.indexes
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy

  palette:
    # - media: "(prefers-color-scheme: dark)"
    - scheme: default
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # - media: "(prefers-color-scheme: light)"
    - scheme: slate
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/curvefi
      name: Telegram
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/curvefinance
      name: X
    - icon: fontawesome/brands/discord
      link: https://discord.gg/rgrfS7W
      name: Discord
    - icon: fontawesome/brands/youtube
      link: http://www.youtube.com/c/CurveFinance
      name: YouTube

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_name: CurveDocs/curve-resources
repo_url: https://github.com/CurveDocs/curve-resources


nav:
  - Главная: index.md
  - Начало работы:
    - Понимание Curve & Stableswap (v1): base-features/understanding-curve.md  
    - Понимание Cryptoswap (v2): base-features/understanding-crypto-pools.md

  - Токен CRV:
    - Обзор & Токеномика: crv-token/overview.md
    - Предложение & Распределение: crv-token/supply-distribution.md
    - CRV & veCRV FAQ: crv-token/faq.md

  - Заблокированный CRV (veCRV):
    - Обзор: vecrv/overview.md
    - Как заблокировать CRV: vecrv/locking-your-crv.md
    - Получение торговых комиссий: vecrv/claiming-trading-fees.md
    - Сбор и распределение комиссий: vecrv/fee-collection-distribution.md

  - Стейблкоин Curve (crvUSD):
    - Понимание crvUSD: crvusd/understanding-crvusd.md
    - Создание и управление займом: crvusd/loan-creation.md
    - Ликвидации: crvusd/liquidations.md
    - Стратегии займов: crvusd/loan-strategies.md
    - Глубокое понимание концепций займа: crvusd/loan-concepts.md
    - FAQ по crvUSD: crvusd/faq.md

  - Доходный-crvUSD (scrvUSD): crvusd/scrvusd.md

  - Кредитование Curve:
    - Обзор: lending/overview.md
    - Кредитное плечо: lending/leverage.md
    - Ликвидации: crvusd/liquidations.md
    - Как заимствовать и использовать кредитное плечо: lending/how-to-borrow.md
    - Как поставлять ликвидность: lending/how-to-supply.md
    - FAQ по кредитованию: lending/faq.md
    - Как создать кредитный рынок: lending/create-lending-market.md

  - Пулы:
    - Обзор: lp/overview.md
    - FAQ по депозиту: lp/deposit-faqs.md
    - Расчет доходности: lp/calculating-yield.md
    - Графики и активность пулов: lp/charts_poolactivity.md
    - Депонирование:
      - Обзор: lp/depositing/depositing.md
      - Депонирование в tri-pool: lp/depositing/depositing-into-the-tri-pool.md
      - Депонирование в metapool: lp/depositing/depositing-into-a-metapool.md
      - Депонирование в cryptoswap-pool: lp/depositing/depositing-into-a-cryptoswap-pool.md
      - Депонирование в tricrypto-pool: lp/depositing/depositing-into-a-tricrypto-pool.md

  - Создание пулов:
    - Обзор создания пулов: factory-pools/pool-creation-overview.md
    - Создание Stableswap NG пула: factory-pools/creating-a-stableswap-ng-pool.md
    - Создание Twocrypto NG пула: factory-pools/creating-a-twocrypto-ng-pool.md
    - Создание Tricrypto NG пула: factory-pools/creating-a-tricrypto-ng-pool.md
    - Понимание оракулов: factory-pools/understanding-oracles.md

  - Гейджи вознаграждений (Reward Gauges):
    - Обзор: reward-gauges/overview.md
    - Создание гейджа пула: reward-gauges/creating-a-pool-gauge.md
    - Увеличение ваших CRV наград: reward-gauges/boosting-your-crv-rewards.md
    - Весы гейджей: reward-gauges/gauge-weights.md
    - Безразрешительные вознаграждения: reward-gauges/permissionless-rewards.md

  - Управление (Governance):
    - Понимание управления: governance/understanding-governance.md
    - Голосование: governance/voting.md
    - Фонд сообщества: governance/community-fund.md
    - Предложения:
      - Создание предложения DAO: governance/proposals/creating-a-dao-proposal.md

  - Мульти-чейн:
    - CRV: multichain/crv.md
    - crvUSD: multichain/crvusd.md
    - Понимание мульти-чейн: multichain/understanding-multichain.md
    - Перемещение средств между сетями: multichain/bridging-funds.md
    - Как перенести crvUSD на BSC: multichain/bridging-crvusd-to-bsc.md

  - Поддержка и устранение неполадок:
    - Поддержка: troubleshooting/support.md
    - Восстановление кросс-активных обменов: troubleshooting/recovering-a-cross-asset-swap.md
    - Отмена и замена зависшей транзакции: troubleshooting/dropping-and-replacing-a-stuck-transaction.md
    - Отключение криптокошельков в Brave: troubleshooting/disabling-crypto-wallets-in-brave.md

  - Риски, безопасность и аудиты:
    - Риски:
      - Ликвидные пулы: risks-security/risks/pool.md
      - crvUSD: risks-security/risks/crvusd.md
      - Кредитование: risks-security/risks/lending.md
    - Безопасность и аудиты: risks-security/security.md

  - Whitepapers (Белые книги):
    - Curve Stableswap (2019): pdf/curve-stableswap.pdf
    - Curve DAO (2020): pdf/curve-dao.pdf
    - Curve Cryptopools (2021): pdf/curve-cryptopools.pdf
    - Curve Stablecoin (2022): pdf/curve-stablecoin.pdf

  - Ссылки:
    - Curve.fi: https://curve.fi/#/ethereum/swap
    - Curve DAO: https://dao.curve.fi/
    - Curve News: https://news.curve.fi/
    - Discord: https://discord.gg/twUngQYz85
    - Github: https://github.com/curvefi/
    - Форум управления: https://gov.curve.fi/
    - Twitter: https://twitter.com/curvefinance
    - Техническая документация: https://docs.curve.fi/
    - Telegram: https://t.me/curvefi

  - Глоссарий: glossary-branding/glossary.md
  - Брендинг и иконки: glossary-branding/branding.md

